#!/bin/bash

# Manual migration script for eBay time-series tables
# This script provides instructions for applying the migration

echo "════════════════════════════════════════════════════════════════"
echo "eBay Time-Series Migration Application Guide"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Migration file: supabase/migrations/20251204_create_ebay_time_series_tables.sql"
echo ""
echo "OPTION 1: Using Supabase Dashboard (Recommended)"
echo "  1. Go to: https://supabase.com/dashboard"
echo "  2. Select your project"
echo "  3. Go to: SQL Editor"
echo "  4. Copy/paste the contents of:"
echo "     supabase/migrations/20251204_create_ebay_time_series_tables.sql"
echo "  5. Click 'Run'"
echo ""
echo "OPTION 2: Using psql (if installed)"
echo "  psql \"\$DATABASE_URL\" -f supabase/migrations/20251204_create_ebay_time_series_tables.sql"
echo ""
echo "OPTION 3: Using Supabase CLI (if installed)"
echo "  npx supabase db push --db-url \"\$DATABASE_URL\""
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "After applying migration, verify with:"
echo "  SELECT COUNT(*) FROM ebay_sold_transactions;"
echo "  SELECT COUNT(*) FROM ebay_computed_metrics;"
echo ""
echo "Then test the pipeline:"
echo "  node scripts/test-ebay-full-pipeline.mjs DZ4137-700"
echo ""
echo "════════════════════════════════════════════════════════════════"
